### ISSUE TITLE
Implement session management

### ISSUE THREAD

**Issue by Mikerah** [ChainSafe/discv5#15]
Whenever two new peers talk for the first time, a session needs to be initiated and stored so that subsequent conversations are appropriately encrypted.

We need to generate session keys whenever 2 peers talk for the first time and store them. These are ECDH keys (use typescript fork of milagro-crypto-js). Once a session has been established, peers communicate using as usual but their messages are encrypted using AES-GCM.

**Comment by Mikerah** [comment]
Before working on ECDH, I need to find an appropriate HKDF library that works with milagro-crypto. Current contenders are [jscu's hkdf implementation](https://github.com/junkurihara/jscu/tree/master/packages/js-crypto-hkdf) and [futoin's hkdf implementation](https://github.com/futoin/util-js-hkdf).

Things to consider:
- Types used in both libraries and how they fit in with milagro-crypto
- Formats of various buffers
- Whether the functions are constant time when composed.

**Comment by Mikerah** [comment]
Currently, there's a temp object for ENR Key Pairs that needs to be reconciled with libp2p key pairs. The types of key pairs libp2p supports are RSA, ED25519 and SECP256K1. However, currently js-libp2p-crypto only supports a few cipher modes for AES. Support is provided by the default node.js crypto library. Will need to submit changes to js-libp2p-crypto to allow for AES-GCM.

**Comment by Mikerah** [comment]
Session management crypto is done. Only need to implement the actual session stuff next.

**Comment by wemeetagain** [comment]
resolved in v0.1.0
