### ISSUE TITLE
Session is being established

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/discv5#153]
As noted in https://github.com/ChainSafe/lodestar/issues/3423#issuecomment-966793785, if we send an authentication message to the other node but it does not response, the pending Session stays there and we always get `Session is being established, request failed` error for subsequent requests

With a session timeout of `sessionTimeout: 86400 * 1000`, it'd take 1 day for the next handshake in order to establish a session.

**Comment by dapplion** [comment]
Definitely the timeout for pending sessions should be way shorter

**Comment by philknows** [comment]
Closing as stale.
