### ISSUE TITLE
Implement Query management

### ISSUE THREAD

**Issue by Mikerah** [ChainSafe/discv5#19]
In discv5, there are topic queries needed to retrieve certain information from other nodes. Need to implement all necessary functionality needed to do this.

**Comment by Mikerah** [comment]
Turns out there is no need to implement this from scratch. Libp2p's [kademlia](https://github.com/libp2p/js-libp2p-kad-dht) implementation provides out of the box.

**Comment by wemeetagain** [comment]
resolved in v0.1.0
