### ISSUE TITLE
Abort timeout in TimeoutMap

### ISSUE THREAD

**Issue by 3xtr4t3rr3str14l** [ChainSafe/discv5#97]
As per the effort to track and close open handles in lodestar (issue tracked here: https://github.com/ChainSafe/lodestar/issues/1466), we need to abort the timeout set in timeoutmap.js (maybe via an AbortSignal/AbortController) because it is showing up as an open handle when sending SIGINT (via Ctrl+C) to the beacon node using wtfnode.

This particular timeout is here:
https://github.com/ChainSafe/discv5/blob/30b77d9c3c745e2345abb2deb8e1d0b19006b62b/src/util/timeoutMap.ts#L22

An example of a log as seen by using wtfnode on the beacon node is as such
```
(86400000 ~ 24 hr) (anonymous) @ /home/seraph/work/ChainSafe/lodestar/node_modules/@chainsafe/discv5/lib/util/timeoutMap.js:19
```

**Comment by wemeetagain** [comment]
We should be closing all timeouts in [`TimeoutMap#clear`](https://github.com/ChainSafe/discv5/blob/master/src/util/timeoutMap.ts#L58) which gets called in [`SessionService#stop`](https://github.com/ChainSafe/discv5/blob/master/src/session/service.ts#L115) which gets called in [`Discv5#stop`](https://github.com/ChainSafe/discv5/blob/master/src/service/service.ts#L198).

I think its likely that somehow discv5 hasn't been shut down when the sample was taken.
